/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Abs_Ramp_struct.H"
#include "wiglafNode.H"

Abs_Ramp_struct::Abs_Ramp_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Abs_Ramp");
}

void Abs_Ramp_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    Etemp_n = (child++)->getIntValue();
    Etemp = (child++)->getDoubleValue();
    Etemp_min = (child++)->getDoubleValue();
    Etemp_max = (child++)->getDoubleValue();
    Efermi_n = (child++)->getIntValue();
    Efermi = (child++)->getDoubleValue();
    Efermi_min = (child++)->getDoubleValue();
    Efermi_max = (child++)->getDoubleValue();
    Estrength_n = (child++)->getIntValue();
    Estrength = (child++)->getDoubleValue();
    Estrength_min = (child++)->getDoubleValue();
    Estrength_max = (child++)->getDoubleValue();
    Ephi_n = (child++)->getIntValue();
    Ephi = (child++)->getDoubleValue();
    Ephi_min = (child++)->getDoubleValue();
    Ephi_max = (child++)->getDoubleValue();
    Etheta_n = (child++)->getIntValue();
    Etheta = (child++)->getDoubleValue();
    Etheta_min = (child++)->getDoubleValue();
    Etheta_max = (child++)->getDoubleValue();

}

void Abs_Ramp_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Abs_Ramp_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            Etemp_n = (child++)->getIntValue();
            Etemp = (child++)->getDoubleValue();
            Etemp_min = (child++)->getDoubleValue();
            Etemp_max = (child++)->getDoubleValue();
            Efermi_n = (child++)->getIntValue();
            Efermi = (child++)->getDoubleValue();
            Efermi_min = (child++)->getDoubleValue();
            Efermi_max = (child++)->getDoubleValue();
            Estrength_n = (child++)->getIntValue();
            Estrength = (child++)->getDoubleValue();
            Estrength_min = (child++)->getDoubleValue();
            Estrength_max = (child++)->getDoubleValue();
            Ephi_n = (child++)->getIntValue();
            Ephi = (child++)->getDoubleValue();
            Ephi_min = (child++)->getDoubleValue();
            Ephi_max = (child++)->getDoubleValue();
            Etheta_n = (child++)->getIntValue();
            Etheta = (child++)->getDoubleValue();
            Etheta_min = (child++)->getDoubleValue();
            Etheta_max = (child++)->getDoubleValue();
            break;

        }
        index++;
    }
}

string Abs_Ramp_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Abs_Ramp_struct -----\n");
    sprintf(buffer, "%d", Etemp_n);
    output.append( string(indentSpacesMore) + string("Etemp_n: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etemp);
    output.append( string(indentSpacesMore) + string("Etemp: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etemp_min);
    output.append( string(indentSpacesMore) + string("Etemp_min: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etemp_max);
    output.append( string(indentSpacesMore) + string("Etemp_max: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Efermi_n);
    output.append( string(indentSpacesMore) + string("Efermi_n: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Efermi);
    output.append( string(indentSpacesMore) + string("Efermi: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Efermi_min);
    output.append( string(indentSpacesMore) + string("Efermi_min: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Efermi_max);
    output.append( string(indentSpacesMore) + string("Efermi_max: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Estrength_n);
    output.append( string(indentSpacesMore) + string("Estrength_n: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Estrength);
    output.append( string(indentSpacesMore) + string("Estrength: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Estrength_min);
    output.append( string(indentSpacesMore) + string("Estrength_min: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Estrength_max);
    output.append( string(indentSpacesMore) + string("Estrength_max: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Ephi_n);
    output.append( string(indentSpacesMore) + string("Ephi_n: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ephi);
    output.append( string(indentSpacesMore) + string("Ephi: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ephi_min);
    output.append( string(indentSpacesMore) + string("Ephi_min: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ephi_max);
    output.append( string(indentSpacesMore) + string("Ephi_max: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Etheta_n);
    output.append( string(indentSpacesMore) + string("Etheta_n: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etheta);
    output.append( string(indentSpacesMore) + string("Etheta: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etheta_min);
    output.append( string(indentSpacesMore) + string("Etheta_min: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Etheta_max);
    output.append( string(indentSpacesMore) + string("Etheta_max: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Abs_Ramp_struct -----\n");
    output.append("\n");
    return output;
}


