/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Absorp_struct.H"
#include "wiglafNode.H"

Absorp_struct::Absorp_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Absorp");
}

void Absorp_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    AbsCoeff = (child++)->getBooleanValue();
    IntegrAbs = (child++)->getBooleanValue();
    HbarOverTau = (child++)->getDoubleValue();
    ramp = getrampType((child++)->getStringValue());

}

void Absorp_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Absorp_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            AbsCoeff = (child++)->getBooleanValue();
            IntegrAbs = (child++)->getBooleanValue();
            HbarOverTau = (child++)->getDoubleValue();
            ramp = getrampType((child++)->getStringValue());
            break;

        }
        index++;
    }
}

string Absorp_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Absorp_struct -----\n");
    sprintf(buffer, "%d", AbsCoeff);
    output.append( string(indentSpacesMore) + string("AbsCoeff: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", IntegrAbs);
    output.append( string(indentSpacesMore) + string("IntegrAbs: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", HbarOverTau);
    output.append( string(indentSpacesMore) + string("HbarOverTau: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("ramp: enum ") + string(getEnumStringrampType(ramp)) + string("\n") );

    output.append( string(indentSpaces) + "---- End Absorp_struct -----\n");
    output.append("\n");
    return output;
}


