/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "BLanczos_struct.H"
#include "wiglafNode.H"

BLanczos_struct::BLanczos_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/BLanczos");
}

void BLanczos_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    BL_size = (child++)->getIntValue();
    DeflationOn = (child++)->getIntValue();
    DefTolerance = (child++)->getDoubleValue();
    Max_no_success = (child++)->getIntValue();
    Eig_dump = (child++)->getIntValue();
    num_cb = (child++)->getIntValue();
    num_vb = (child++)->getIntValue();
    Dump_blockTridiagonal_Sparse_Matrix_Format = (child++)->getIntValue();
    Dump_blockTridiagonal_Band_Matrix_Format = (child++)->getIntValue();
    Read_blockTridiagonal_Band_Matrix_Format = (child++)->getIntValue();
    ReadInTridiag = (child++)->getBooleanValue();
    ConvTolerance = (child++)->getDoubleValue();
    MaxIter = (child++)->getIntValue();
    conv_method = (child++)->getIntValue();
    conv_vec_method = (child++)->getIntValue();
    NumEigReq_vb = (child++)->getIntValue();
    Erange_vb = (child++)->getVectorDoubleValue();
    Erange_cb = (child++)->getVectorDoubleValue();
    NumEigReq_cb = (child++)->getIntValue();
    ConvCheckStartIter = (child++)->getIntValue();
    ConvCheckSkipRate = (child++)->getIntValue();
    Start = getStartType((child++)->getStringValue());
    StartFileRead = (child++)->getStringValue();
    ConvSingleValue = (child++)->getIntValue();
    CyclicString = (child++)->getVectorDoubleValue();

}

void BLanczos_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "BLanczos_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            BL_size = (child++)->getIntValue();
            DeflationOn = (child++)->getIntValue();
            DefTolerance = (child++)->getDoubleValue();
            Max_no_success = (child++)->getIntValue();
            Eig_dump = (child++)->getIntValue();
            num_cb = (child++)->getIntValue();
            num_vb = (child++)->getIntValue();
            Dump_blockTridiagonal_Sparse_Matrix_Format = (child++)->getIntValue();
            Dump_blockTridiagonal_Band_Matrix_Format = (child++)->getIntValue();
            Read_blockTridiagonal_Band_Matrix_Format = (child++)->getIntValue();
            ReadInTridiag = (child++)->getBooleanValue();
            ConvTolerance = (child++)->getDoubleValue();
            MaxIter = (child++)->getIntValue();
            conv_method = (child++)->getIntValue();
            conv_vec_method = (child++)->getIntValue();
            NumEigReq_vb = (child++)->getIntValue();
            Erange_vb = (child++)->getVectorDoubleValue();
            Erange_cb = (child++)->getVectorDoubleValue();
            NumEigReq_cb = (child++)->getIntValue();
            ConvCheckStartIter = (child++)->getIntValue();
            ConvCheckSkipRate = (child++)->getIntValue();
            Start = getStartType((child++)->getStringValue());
            StartFileRead = (child++)->getStringValue();
            ConvSingleValue = (child++)->getIntValue();
            CyclicString = (child++)->getVectorDoubleValue();
            break;

        }
        index++;
    }
}

string BLanczos_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin BLanczos_struct -----\n");
    sprintf(buffer, "%d", BL_size);
    output.append( string(indentSpacesMore) + string("BL_size: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", DeflationOn);
    output.append( string(indentSpacesMore) + string("DeflationOn: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", DefTolerance);
    output.append( string(indentSpacesMore) + string("DefTolerance: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Max_no_success);
    output.append( string(indentSpacesMore) + string("Max_no_success: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Eig_dump);
    output.append( string(indentSpacesMore) + string("Eig_dump: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", num_cb);
    output.append( string(indentSpacesMore) + string("num_cb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", num_vb);
    output.append( string(indentSpacesMore) + string("num_vb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Dump_blockTridiagonal_Sparse_Matrix_Format);
    output.append( string(indentSpacesMore) + string("Dump_blockTridiagonal_Sparse_Matrix_Format: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Dump_blockTridiagonal_Band_Matrix_Format);
    output.append( string(indentSpacesMore) + string("Dump_blockTridiagonal_Band_Matrix_Format: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Read_blockTridiagonal_Band_Matrix_Format);
    output.append( string(indentSpacesMore) + string("Read_blockTridiagonal_Band_Matrix_Format: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", ReadInTridiag);
    output.append( string(indentSpacesMore) + string("ReadInTridiag: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", ConvTolerance);
    output.append( string(indentSpacesMore) + string("ConvTolerance: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", MaxIter);
    output.append( string(indentSpacesMore) + string("MaxIter: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", conv_method);
    output.append( string(indentSpacesMore) + string("conv_method: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", conv_vec_method);
    output.append( string(indentSpacesMore) + string("conv_vec_method: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NumEigReq_vb);
    output.append( string(indentSpacesMore) + string("NumEigReq_vb: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=Erange_vb.begin(); item != Erange_vb.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "Erange_vb[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=Erange_cb.begin(); item != Erange_cb.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "Erange_cb[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%d", NumEigReq_cb);
    output.append( string(indentSpacesMore) + string("NumEigReq_cb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", ConvCheckStartIter);
    output.append( string(indentSpacesMore) + string("ConvCheckStartIter: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", ConvCheckSkipRate);
    output.append( string(indentSpacesMore) + string("ConvCheckSkipRate: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("Start: enum ") + string(getEnumStringStartType(Start)) + string("\n") );
    output.append( string(indentSpacesMore) + string("StartFileRead: \"") + StartFileRead + string("\"\n"));
    sprintf(buffer, "%d", ConvSingleValue);
    output.append( string(indentSpacesMore) + string("ConvSingleValue: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=CyclicString.begin(); item != CyclicString.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "CyclicString[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }

    output.append( string(indentSpaces) + "---- End BLanczos_struct -----\n");
    output.append("\n");
    return output;
}


