/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Dev_struct.H"
#include "wiglafNode.H"

Dev_struct::Dev_struct(const DOM_Node& dn) {
    set(dn,"/top/Geometric info");
}

void Dev_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    StructFile = (child++)->getStringValue();
    CrystalStruct = getCrystalStructType((child++)->getStringValue());
    band_model = getband_modelType((child++)->getStringValue());
    a_lattice_x = (child++)->getDoubleValue();
    a_lattice_y = (child++)->getDoubleValue();
    a_lattice_z = (child++)->getDoubleValue();
    tilt_hkl = (child++)->getBooleanValue();
    tilt_h = (child++)->getIntValue();
    tilt_k = (child++)->getIntValue();
    tilt_l = (child++)->getIntValue();
    NaddALY = (child++)->getIntValue();
    NaddALZ = (child++)->getIntValue();

    vector<wiglafNode> allGroupsInTypeStruct = w.getChildren(isGroup);
    Shape_struct item;
    for (vector<wiglafNode>::iterator groupInTypeStruct = allGroupsInTypeStruct.begin(); groupInTypeStruct != allGroupsInTypeStruct.end(); groupInTypeStruct++ ) {
        if ( groupInTypeStruct->getAttribute("type").equals("array") ) {
            int offset = 0;
            vector<wiglafNode> allGroupsInTypeArray = groupInTypeStruct->getChildren(isGroup);
            for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
                if ( groupInTypeArray->getAttribute("type").equals("obj") ) {
                    item.setFromArrayElement(dn,groupInTypeStruct->getPathToRoot(),offset++);
                    ShapeList.push_back(item);
                }
            }
        }
    }
}

void Dev_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Dev_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            StructFile = (child++)->getStringValue();
            CrystalStruct = getCrystalStructType((child++)->getStringValue());
            band_model = getband_modelType((child++)->getStringValue());
            a_lattice_x = (child++)->getDoubleValue();
            a_lattice_y = (child++)->getDoubleValue();
            a_lattice_z = (child++)->getDoubleValue();
            tilt_hkl = (child++)->getBooleanValue();
            tilt_h = (child++)->getIntValue();
            tilt_k = (child++)->getIntValue();
            tilt_l = (child++)->getIntValue();
            NaddALY = (child++)->getIntValue();
            NaddALZ = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string Dev_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Dev_struct -----\n");
    output.append( string(indentSpacesMore) + string("StructFile: \"") + StructFile + string("\"\n"));
    output.append( string(indentSpacesMore) + string("CrystalStruct: enum ") + string(getEnumStringCrystalStructType(CrystalStruct)) + string("\n") );
    output.append( string(indentSpacesMore) + string("band_model: enum ") + string(getEnumStringband_modelType(band_model)) + string("\n") );
    sprintf(buffer, "%f", a_lattice_x);
    output.append( string(indentSpacesMore) + string("a_lattice_x: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", a_lattice_y);
    output.append( string(indentSpacesMore) + string("a_lattice_y: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", a_lattice_z);
    output.append( string(indentSpacesMore) + string("a_lattice_z: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", tilt_hkl);
    output.append( string(indentSpacesMore) + string("tilt_hkl: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", tilt_h);
    output.append( string(indentSpacesMore) + string("tilt_h: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", tilt_k);
    output.append( string(indentSpacesMore) + string("tilt_k: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", tilt_l);
    output.append( string(indentSpacesMore) + string("tilt_l: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NaddALY);
    output.append( string(indentSpacesMore) + string("NaddALY: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NaddALZ);
    output.append( string(indentSpacesMore) + string("NaddALZ: ") + string(buffer) + string("\n"));

    for (vector<Shape_struct>::iterator item = ShapeList.begin(); item != ShapeList.end(); item++ ) {
        output.append( item->toString(indentLength) );
    }
    output.append( string(indentSpaces) + "---- End Dev_struct -----\n");
    output.append("\n");
    return output;
}


