/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ElAlg_struct.H"
#include "wiglafNode.H"

ElAlg_struct::ElAlg_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms");
}

void ElAlg_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    ResFind = getResFindType((child++)->getStringValue());
    Nk = (child++)->getIntValue();
    k0 = (child++)->getVectorDoubleValue();
    kf = (child++)->getVectorDoubleValue();
    HamCompute = getHamComputeType((child++)->getStringValue());
    HamSize = getHamSizeType((child++)->getStringValue());
    Efficiency = getEfficiencyType((child++)->getStringValue());

    Lanczos.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/Lanczos");
    BLanczos.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/BLanczos");
    RayleighRitz.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/Rayleigh-Ritz");
    Parpack.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/Parpack");
    PQTracemin.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/PQTracemin");
    PCTracemin.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/PCTracemin");
    ReadInEigen.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/ReadInEigen");
}

void ElAlg_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ElAlg_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            ResFind = getResFindType((child++)->getStringValue());
            Nk = (child++)->getIntValue();
            k0 = (child++)->getVectorDoubleValue();
            kf = (child++)->getVectorDoubleValue();
            HamCompute = getHamComputeType((child++)->getStringValue());
            HamSize = getHamSizeType((child++)->getStringValue());
            Efficiency = getEfficiencyType((child++)->getStringValue());
            break;

        }
        index++;
    }
}

string ElAlg_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ElAlg_struct -----\n");
    output.append( string(indentSpacesMore) + string("ResFind: enum ") + string(getEnumStringResFindType(ResFind)) + string("\n") );
    sprintf(buffer, "%d", Nk);
    output.append( string(indentSpacesMore) + string("Nk: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=k0.begin(); item != k0.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "k0[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=kf.begin(); item != kf.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "kf[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    output.append( string(indentSpacesMore) + string("HamCompute: enum ") + string(getEnumStringHamComputeType(HamCompute)) + string("\n") );
    output.append( string(indentSpacesMore) + string("HamSize: enum ") + string(getEnumStringHamSizeType(HamSize)) + string("\n") );
    output.append( string(indentSpacesMore) + string("Efficiency: enum ") + string(getEnumStringEfficiencyType(Efficiency)) + string("\n") );

    output.append( Lanczos.toString(indentLength) );
    output.append( BLanczos.toString(indentLength) );
    output.append( RayleighRitz.toString(indentLength) );
    output.append( Parpack.toString(indentLength) );
    output.append( PQTracemin.toString(indentLength) );
    output.append( PCTracemin.toString(indentLength) );
    output.append( ReadInEigen.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End ElAlg_struct -----\n");
    output.append("\n");
    return output;
}


