/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ElCalc_struct.H"
#include "wiglafNode.H"

ElCalc_struct::ElCalc_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation");
}

void ElCalc_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    include_strain_in_Hamiltonian = (child++)->getBooleanValue();

    ElGeo.set(dn,"/top/Execution parameters/Electronic structure calculation/Modifications to geometry");
    ElAlg.set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms");
    ElOut.set(dn,"/top/Execution parameters/Electronic structure calculation/Output");
}

void ElCalc_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ElCalc_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            include_strain_in_Hamiltonian = (child++)->getBooleanValue();
            break;

        }
        index++;
    }
}

string ElCalc_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ElCalc_struct -----\n");
    sprintf(buffer, "%d", include_strain_in_Hamiltonian);
    output.append( string(indentSpacesMore) + string("include_strain_in_Hamiltonian: ") + string(buffer) + string("\n"));

    output.append( ElGeo.toString(indentLength) );
    output.append( ElAlg.toString(indentLength) );
    output.append( ElOut.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End ElCalc_struct -----\n");
    output.append("\n");
    return output;
}


