/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ElGeo_struct.H"
#include "wiglafNode.H"

ElGeo_struct::ElGeo_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Modifications to geometry");
}

void ElGeo_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    Periodicity = getPeriodicityType((child++)->getStringValue());
    HomogenizeSurface = (child++)->getBooleanValue();
    RemoveSingleBonds = (child++)->getBooleanValue();

}

void ElGeo_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ElGeo_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            Periodicity = getPeriodicityType((child++)->getStringValue());
            HomogenizeSurface = (child++)->getBooleanValue();
            RemoveSingleBonds = (child++)->getBooleanValue();
            break;

        }
        index++;
    }
}

string ElGeo_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ElGeo_struct -----\n");
    output.append( string(indentSpacesMore) + string("Periodicity: enum ") + string(getEnumStringPeriodicityType(Periodicity)) + string("\n") );
    sprintf(buffer, "%d", HomogenizeSurface);
    output.append( string(indentSpacesMore) + string("HomogenizeSurface: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", RemoveSingleBonds);
    output.append( string(indentSpacesMore) + string("RemoveSingleBonds: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End ElGeo_struct -----\n");
    output.append("\n");
    return output;
}


