/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ElOut_struct.H"
#include "wiglafNode.H"

ElOut_struct::ElOut_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Output");
}

void ElOut_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    EnergyDispersion = (child++)->getBooleanValue();
    Eigvect = (child++)->getBooleanValue();
    PsiSqr = (child++)->getBooleanValue();
    PsiSqr_cell = (child++)->getBooleanValue();
    Visualization_3D = (child++)->getBooleanValue();
    LocalBands = (child++)->getBooleanValue();
    SaveTridiagInfo = (child++)->getBooleanValue();
    TraceEigval = (child++)->getBooleanValue();
    CGiter_log = (child++)->getBooleanValue();
    CGiter_log2 = (child++)->getBooleanValue();
    LocalHam = (child++)->getBooleanValue();
    PsiSqrPdb = (child++)->getBooleanValue();
    PsiSqrCutoffPdb = (child++)->getDoubleValue();
    StructurePdb = (child++)->getBooleanValue();
    StructureGmv = (child++)->getBooleanValue();
    StructureCubicGmv = (child++)->getBooleanValue();
    Psi4_IPR = (child++)->getBooleanValue();
    OptMatrixEl = (child++)->getBooleanValue();
    Absorption = (child++)->getBooleanValue();
    LogLevel = (child++)->getIntValue();

}

void ElOut_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ElOut_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            EnergyDispersion = (child++)->getBooleanValue();
            Eigvect = (child++)->getBooleanValue();
            PsiSqr = (child++)->getBooleanValue();
            PsiSqr_cell = (child++)->getBooleanValue();
            Visualization_3D = (child++)->getBooleanValue();
            LocalBands = (child++)->getBooleanValue();
            SaveTridiagInfo = (child++)->getBooleanValue();
            TraceEigval = (child++)->getBooleanValue();
            CGiter_log = (child++)->getBooleanValue();
            CGiter_log2 = (child++)->getBooleanValue();
            LocalHam = (child++)->getBooleanValue();
            PsiSqrPdb = (child++)->getBooleanValue();
            PsiSqrCutoffPdb = (child++)->getDoubleValue();
            StructurePdb = (child++)->getBooleanValue();
            StructureGmv = (child++)->getBooleanValue();
            StructureCubicGmv = (child++)->getBooleanValue();
            Psi4_IPR = (child++)->getBooleanValue();
            OptMatrixEl = (child++)->getBooleanValue();
            Absorption = (child++)->getBooleanValue();
            LogLevel = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string ElOut_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ElOut_struct -----\n");
    sprintf(buffer, "%d", EnergyDispersion);
    output.append( string(indentSpacesMore) + string("EnergyDispersion: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Eigvect);
    output.append( string(indentSpacesMore) + string("Eigvect: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", PsiSqr);
    output.append( string(indentSpacesMore) + string("PsiSqr: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", PsiSqr_cell);
    output.append( string(indentSpacesMore) + string("PsiSqr_cell: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Visualization_3D);
    output.append( string(indentSpacesMore) + string("Visualization_3D: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LocalBands);
    output.append( string(indentSpacesMore) + string("LocalBands: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", SaveTridiagInfo);
    output.append( string(indentSpacesMore) + string("SaveTridiagInfo: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", TraceEigval);
    output.append( string(indentSpacesMore) + string("TraceEigval: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CGiter_log);
    output.append( string(indentSpacesMore) + string("CGiter_log: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CGiter_log2);
    output.append( string(indentSpacesMore) + string("CGiter_log2: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LocalHam);
    output.append( string(indentSpacesMore) + string("LocalHam: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", PsiSqrPdb);
    output.append( string(indentSpacesMore) + string("PsiSqrPdb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", PsiSqrCutoffPdb);
    output.append( string(indentSpacesMore) + string("PsiSqrCutoffPdb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", StructurePdb);
    output.append( string(indentSpacesMore) + string("StructurePdb: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", StructureGmv);
    output.append( string(indentSpacesMore) + string("StructureGmv: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", StructureCubicGmv);
    output.append( string(indentSpacesMore) + string("StructureCubicGmv: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Psi4_IPR);
    output.append( string(indentSpacesMore) + string("Psi4_IPR: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", OptMatrixEl);
    output.append( string(indentSpacesMore) + string("OptMatrixEl: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Absorption);
    output.append( string(indentSpacesMore) + string("Absorption: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LogLevel);
    output.append( string(indentSpacesMore) + string("LogLevel: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End ElOut_struct -----\n");
    output.append("\n");
    return output;
}


