/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ExecParam_struct.H"
#include "wiglafNode.H"

ExecParam_struct::ExecParam_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters");
}

void ExecParam_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    CalcStr = (child++)->getBooleanValue();
    CalcElDisp = (child++)->getBooleanValue();
    CalcPhonDisp = (child++)->getBooleanValue();
    RandomSeed = (child++)->getIntValue();

    Phys.set(dn,"/top/Execution parameters/Physical parameters");
    ElCalc.set(dn,"/top/Execution parameters/Electronic structure calculation");
    Strain.set(dn,"/top/Execution parameters/Strain calculation");
    PhonCalc.set(dn,"/top/Execution parameters/Phonon calcuation");
    Output.set(dn,"/top/Execution parameters/Output");
    Subdomain.set(dn,"/top/Execution parameters/Subdomain");
    Absorp.set(dn,"/top/Execution parameters/Absorp");
    Abs_Ramp.set(dn,"/top/Execution parameters/Abs_Ramp");
}

void ExecParam_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ExecParam_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            CalcStr = (child++)->getBooleanValue();
            CalcElDisp = (child++)->getBooleanValue();
            CalcPhonDisp = (child++)->getBooleanValue();
            RandomSeed = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string ExecParam_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ExecParam_struct -----\n");
    sprintf(buffer, "%d", CalcStr);
    output.append( string(indentSpacesMore) + string("CalcStr: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CalcElDisp);
    output.append( string(indentSpacesMore) + string("CalcElDisp: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CalcPhonDisp);
    output.append( string(indentSpacesMore) + string("CalcPhonDisp: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", RandomSeed);
    output.append( string(indentSpacesMore) + string("RandomSeed: ") + string(buffer) + string("\n"));

    output.append( Phys.toString(indentLength) );
    output.append( ElCalc.toString(indentLength) );
    output.append( Strain.toString(indentLength) );
    output.append( PhonCalc.toString(indentLength) );
    output.append( Output.toString(indentLength) );
    output.append( Subdomain.toString(indentLength) );
    output.append( Absorp.toString(indentLength) );
    output.append( Abs_Ramp.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End ExecParam_struct -----\n");
    output.append("\n");
    return output;
}


