/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Keating_struct.H"
#include "wiglafNode.H"

Keating_struct::Keating_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Strain calculation/Keating");
}

void Keating_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    BoundCond = getBoundCondType((child++)->getStringValue());
    Periodicity_strain = getPeriodicity_strainType((child++)->getStringValue());
    MinWrtLatt = getMinWrtLattType((child++)->getStringValue());
    UpdateLatt = (child++)->getBooleanValue();
    UpdateLattConst = (child++)->getVectorDoubleValue();
    SCALE_FCTR = (child++)->getDoubleValue();
    MaxIter = (child++)->getIntValue();
    tol = (child++)->getDoubleValue();
    ConvCrit = getConvCritType((child++)->getStringValue());
    strainCheckPointInterval = (child++)->getIntValue();
    StartFileRead = (child++)->getStringValue();
    verbose = (child++)->getIntValue();

}

void Keating_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Keating_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            BoundCond = getBoundCondType((child++)->getStringValue());
            Periodicity_strain = getPeriodicity_strainType((child++)->getStringValue());
            MinWrtLatt = getMinWrtLattType((child++)->getStringValue());
            UpdateLatt = (child++)->getBooleanValue();
            UpdateLattConst = (child++)->getVectorDoubleValue();
            SCALE_FCTR = (child++)->getDoubleValue();
            MaxIter = (child++)->getIntValue();
            tol = (child++)->getDoubleValue();
            ConvCrit = getConvCritType((child++)->getStringValue());
            strainCheckPointInterval = (child++)->getIntValue();
            StartFileRead = (child++)->getStringValue();
            verbose = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string Keating_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Keating_struct -----\n");
    output.append( string(indentSpacesMore) + string("BoundCond: enum ") + string(getEnumStringBoundCondType(BoundCond)) + string("\n") );
    output.append( string(indentSpacesMore) + string("Periodicity_strain: enum ") + string(getEnumStringPeriodicity_strainType(Periodicity_strain)) + string("\n") );
    output.append( string(indentSpacesMore) + string("MinWrtLatt: enum ") + string(getEnumStringMinWrtLattType(MinWrtLatt)) + string("\n") );
    sprintf(buffer, "%d", UpdateLatt);
    output.append( string(indentSpacesMore) + string("UpdateLatt: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=UpdateLattConst.begin(); item != UpdateLattConst.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "UpdateLattConst[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%f", SCALE_FCTR);
    output.append( string(indentSpacesMore) + string("SCALE_FCTR: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", MaxIter);
    output.append( string(indentSpacesMore) + string("MaxIter: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", tol);
    output.append( string(indentSpacesMore) + string("tol: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("ConvCrit: enum ") + string(getEnumStringConvCritType(ConvCrit)) + string("\n") );
    sprintf(buffer, "%d", strainCheckPointInterval);
    output.append( string(indentSpacesMore) + string("strainCheckPointInterval: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("StartFileRead: \"") + StartFileRead + string("\"\n"));
    sprintf(buffer, "%d", verbose);
    output.append( string(indentSpacesMore) + string("verbose: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Keating_struct -----\n");
    output.append("\n");
    return output;
}


