/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Material_struct.H"
#include "wiglafNode.H"

Material_struct::Material_struct(const DOM_Node& dn) {
    set(dn,"/top/Materials List/Add a material/material");
}

void Material_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    material = (child++)->getStringValue();
    comp1_mat = (child++)->getStringValue();
    xval = (child++)->getDoubleValue();
    comp2_mat = (child++)->getStringValue();
    yval = (child++)->getDoubleValue();
    tkel = (child++)->getDoubleValue();
    substrate = (child++)->getStringValue();
    Ec = (child++)->getDoubleValue();
    Ev = (child++)->getDoubleValue();
    mstar_c_dos = (child++)->getDoubleValue();
    mstar_v_dos = (child++)->getDoubleValue();
    epsilon = (child++)->getDoubleValue();
    unstrnd_cubic_cell_length = (child++)->getDoubleValue();
    strain_alpha = (child++)->getDoubleValue();
    strain_beta = (child++)->getDoubleValue();
    strain_VFF = (child++)->getVectorDoubleValue();
    M_atom = (child++)->getVectorDoubleValue();
    band_model = (child++)->getStringValue();
    mb_pv = (child++)->getVectorDoubleValue();
    Ev_offset = (child++)->getDoubleValue();
    mb_strain = (child++)->getVectorDoubleValue();

}

void Material_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Material_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            material = (child++)->getStringValue();
            comp1_mat = (child++)->getStringValue();
            xval = (child++)->getDoubleValue();
            comp2_mat = (child++)->getStringValue();
            yval = (child++)->getDoubleValue();
            tkel = (child++)->getDoubleValue();
            substrate = (child++)->getStringValue();
            Ec = (child++)->getDoubleValue();
            Ev = (child++)->getDoubleValue();
            mstar_c_dos = (child++)->getDoubleValue();
            mstar_v_dos = (child++)->getDoubleValue();
            epsilon = (child++)->getDoubleValue();
            unstrnd_cubic_cell_length = (child++)->getDoubleValue();
            strain_alpha = (child++)->getDoubleValue();
            strain_beta = (child++)->getDoubleValue();
            strain_VFF = (child++)->getVectorDoubleValue();
            M_atom = (child++)->getVectorDoubleValue();
            band_model = (child++)->getStringValue();
            mb_pv = (child++)->getVectorDoubleValue();
            Ev_offset = (child++)->getDoubleValue();
            mb_strain = (child++)->getVectorDoubleValue();
            break;

        }
        index++;
    }
}

string Material_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Material_struct -----\n");
    output.append( string(indentSpacesMore) + string("material: \"") + material + string("\"\n"));
    output.append( string(indentSpacesMore) + string("comp1_mat: \"") + comp1_mat + string("\"\n"));
    sprintf(buffer, "%f", xval);
    output.append( string(indentSpacesMore) + string("xval: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("comp2_mat: \"") + comp2_mat + string("\"\n"));
    sprintf(buffer, "%f", yval);
    output.append( string(indentSpacesMore) + string("yval: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", tkel);
    output.append( string(indentSpacesMore) + string("tkel: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("substrate: \"") + substrate + string("\"\n"));
    sprintf(buffer, "%f", Ec);
    output.append( string(indentSpacesMore) + string("Ec: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ev);
    output.append( string(indentSpacesMore) + string("Ev: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", mstar_c_dos);
    output.append( string(indentSpacesMore) + string("mstar_c_dos: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", mstar_v_dos);
    output.append( string(indentSpacesMore) + string("mstar_v_dos: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", epsilon);
    output.append( string(indentSpacesMore) + string("epsilon: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", unstrnd_cubic_cell_length);
    output.append( string(indentSpacesMore) + string("unstrnd_cubic_cell_length: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", strain_alpha);
    output.append( string(indentSpacesMore) + string("strain_alpha: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", strain_beta);
    output.append( string(indentSpacesMore) + string("strain_beta: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=strain_VFF.begin(); item != strain_VFF.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "strain_VFF[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=M_atom.begin(); item != M_atom.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "M_atom[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    output.append( string(indentSpacesMore) + string("band_model: \"") + band_model + string("\"\n"));
    i = 0;
    for (vector<double>::iterator item=mb_pv.begin(); item != mb_pv.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "mb_pv[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%f", Ev_offset);
    output.append( string(indentSpacesMore) + string("Ev_offset: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=mb_strain.begin(); item != mb_strain.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "mb_strain[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }

    output.append( string(indentSpaces) + "---- End Material_struct -----\n");
    output.append("\n");
    return output;
}


