/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Output_struct.H"
#include "wiglafNode.H"

Output_struct::Output_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Output");
}

void Output_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    AtomInfo = (child++)->getBooleanValue();
    NbrIndx = (child++)->getBooleanValue();
    AtomPosBeforeStrain = (child++)->getBooleanValue();
    AtomPosEquil = (child++)->getBooleanValue();
    AtomPosAfterStrain = (child++)->getBooleanValue();
    ShapeInfo = (child++)->getBooleanValue();
    RunFile = (child++)->getBooleanValue();
    LogLevel = (child++)->getIntValue();

}

void Output_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Output_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            AtomInfo = (child++)->getBooleanValue();
            NbrIndx = (child++)->getBooleanValue();
            AtomPosBeforeStrain = (child++)->getBooleanValue();
            AtomPosEquil = (child++)->getBooleanValue();
            AtomPosAfterStrain = (child++)->getBooleanValue();
            ShapeInfo = (child++)->getBooleanValue();
            RunFile = (child++)->getBooleanValue();
            LogLevel = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string Output_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Output_struct -----\n");
    sprintf(buffer, "%d", AtomInfo);
    output.append( string(indentSpacesMore) + string("AtomInfo: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NbrIndx);
    output.append( string(indentSpacesMore) + string("NbrIndx: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", AtomPosBeforeStrain);
    output.append( string(indentSpacesMore) + string("AtomPosBeforeStrain: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", AtomPosEquil);
    output.append( string(indentSpacesMore) + string("AtomPosEquil: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", AtomPosAfterStrain);
    output.append( string(indentSpacesMore) + string("AtomPosAfterStrain: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", ShapeInfo);
    output.append( string(indentSpacesMore) + string("ShapeInfo: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", RunFile);
    output.append( string(indentSpacesMore) + string("RunFile: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LogLevel);
    output.append( string(indentSpacesMore) + string("LogLevel: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Output_struct -----\n");
    output.append("\n");
    return output;
}


