/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Parpack_struct.H"
#include "wiglafNode.H"

Parpack_struct::Parpack_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/Parpack");
}

void Parpack_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    MaxIter = (child++)->getIntValue();
    NumEigVal = (child++)->getIntValue();
    NumArnoldiVector = (child++)->getIntValue();
    RefEigVal = (child++)->getDoubleValue();
    Tolerance = (child++)->getDoubleValue();
    CalEigVec = (child++)->getBooleanValue();

}

void Parpack_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Parpack_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            MaxIter = (child++)->getIntValue();
            NumEigVal = (child++)->getIntValue();
            NumArnoldiVector = (child++)->getIntValue();
            RefEigVal = (child++)->getDoubleValue();
            Tolerance = (child++)->getDoubleValue();
            CalEigVec = (child++)->getBooleanValue();
            break;

        }
        index++;
    }
}

string Parpack_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Parpack_struct -----\n");
    sprintf(buffer, "%d", MaxIter);
    output.append( string(indentSpacesMore) + string("MaxIter: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NumEigVal);
    output.append( string(indentSpacesMore) + string("NumEigVal: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", NumArnoldiVector);
    output.append( string(indentSpacesMore) + string("NumArnoldiVector: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", RefEigVal);
    output.append( string(indentSpacesMore) + string("RefEigVal: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Tolerance);
    output.append( string(indentSpacesMore) + string("Tolerance: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CalEigVec);
    output.append( string(indentSpacesMore) + string("CalEigVec: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Parpack_struct -----\n");
    output.append("\n");
    return output;
}


