/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "PCTracemin_struct.H"
#include "wiglafNode.H"

PCTracemin_struct::PCTracemin_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/PCTracemin");
}

void PCTracemin_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    NumEigVal = (child++)->getIntValue();
    RefEigVal = (child++)->getDoubleValue();
    Tolerance = (child++)->getDoubleValue();
    WantEigRange = (child++)->getVectorDoubleValue();
    AllEigRange = (child++)->getVectorDoubleValue();
    maxi = (child++)->getIntValue();
    ChebyDeg = (child++)->getIntValue();
    CalEigVec = (child++)->getBooleanValue();

}

void PCTracemin_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "PCTracemin_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            NumEigVal = (child++)->getIntValue();
            RefEigVal = (child++)->getDoubleValue();
            Tolerance = (child++)->getDoubleValue();
            WantEigRange = (child++)->getVectorDoubleValue();
            AllEigRange = (child++)->getVectorDoubleValue();
            maxi = (child++)->getIntValue();
            ChebyDeg = (child++)->getIntValue();
            CalEigVec = (child++)->getBooleanValue();
            break;

        }
        index++;
    }
}

string PCTracemin_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin PCTracemin_struct -----\n");
    sprintf(buffer, "%d", NumEigVal);
    output.append( string(indentSpacesMore) + string("NumEigVal: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", RefEigVal);
    output.append( string(indentSpacesMore) + string("RefEigVal: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Tolerance);
    output.append( string(indentSpacesMore) + string("Tolerance: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=WantEigRange.begin(); item != WantEigRange.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "WantEigRange[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=AllEigRange.begin(); item != AllEigRange.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "AllEigRange[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%d", maxi);
    output.append( string(indentSpacesMore) + string("maxi: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", ChebyDeg);
    output.append( string(indentSpacesMore) + string("ChebyDeg: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", CalEigVec);
    output.append( string(indentSpacesMore) + string("CalEigVec: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End PCTracemin_struct -----\n");
    output.append("\n");
    return output;
}


