/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "PhonCalc_struct.H"
#include "wiglafNode.H"

PhonCalc_struct::PhonCalc_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Phonon calcuation");
}

void PhonCalc_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    PhonModel = getPhonModelType((child++)->getStringValue());
    q_ph_min = (child++)->getVectorDoubleValue();
    q_ph_max = (child++)->getVectorDoubleValue();
    Nq_ph = (child++)->getIntValue();
    PS = getPSType((child++)->getStringValue());
    anh = getanhType((child++)->getStringValue());
    N_branches = (child++)->getIntValue();

    PhonParpack.set(dn,"/top/Execution parameters/Phonon calcuation/Parpack");
    PhonTracemin.set(dn,"/top/Execution parameters/Phonon calcuation/Tracemin");
    PhonOut.set(dn,"/top/Execution parameters/Phonon calcuation/Output");
}

void PhonCalc_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "PhonCalc_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            PhonModel = getPhonModelType((child++)->getStringValue());
            q_ph_min = (child++)->getVectorDoubleValue();
            q_ph_max = (child++)->getVectorDoubleValue();
            Nq_ph = (child++)->getIntValue();
            PS = getPSType((child++)->getStringValue());
            anh = getanhType((child++)->getStringValue());
            N_branches = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string PhonCalc_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin PhonCalc_struct -----\n");
    output.append( string(indentSpacesMore) + string("PhonModel: enum ") + string(getEnumStringPhonModelType(PhonModel)) + string("\n") );
    i = 0;
    for (vector<double>::iterator item=q_ph_min.begin(); item != q_ph_min.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "q_ph_min[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=q_ph_max.begin(); item != q_ph_max.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "q_ph_max[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%d", Nq_ph);
    output.append( string(indentSpacesMore) + string("Nq_ph: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("PS: enum ") + string(getEnumStringPSType(PS)) + string("\n") );
    output.append( string(indentSpacesMore) + string("anh: enum ") + string(getEnumStringanhType(anh)) + string("\n") );
    sprintf(buffer, "%d", N_branches);
    output.append( string(indentSpacesMore) + string("N_branches: ") + string(buffer) + string("\n"));

    output.append( PhonParpack.toString(indentLength) );
    output.append( PhonTracemin.toString(indentLength) );
    output.append( PhonOut.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End PhonCalc_struct -----\n");
    output.append("\n");
    return output;
}


