/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "PhonOut_struct.H"
#include "wiglafNode.H"

PhonOut_struct::PhonOut_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Phonon calcuation/Output");
}

void PhonOut_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    PhonEq = (child++)->getBooleanValue();
    PhonDV = (child++)->getBooleanValue();
    LogLevel = (child++)->getIntValue();

}

void PhonOut_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "PhonOut_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            PhonEq = (child++)->getBooleanValue();
            PhonDV = (child++)->getBooleanValue();
            LogLevel = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string PhonOut_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin PhonOut_struct -----\n");
    sprintf(buffer, "%d", PhonEq);
    output.append( string(indentSpacesMore) + string("PhonEq: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", PhonDV);
    output.append( string(indentSpacesMore) + string("PhonDV: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LogLevel);
    output.append( string(indentSpacesMore) + string("LogLevel: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End PhonOut_struct -----\n");
    output.append("\n");
    return output;
}


