/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Phys_struct.H"
#include "wiglafNode.H"

Phys_struct::Phys_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Physical parameters");
}

void Phys_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    PotentialFile = (child++)->getStringValue();
    MagneticFieldOn = (child++)->getBooleanValue();
    Bx = (child++)->getDoubleValue();
    By = (child++)->getDoubleValue();
    Bz = (child++)->getDoubleValue();
    Bgauge = (child++)->getStringValue();
    ImpNumber = (child++)->getIntValue();
    ImpsXYZ = (child++)->getVectorDoubleValue();
    imp_model = (child++)->getIntValue();
    include_nuclear_term = (child++)->getBooleanValue();
    EfieldON = (child++)->getBooleanValue();
    Ex = (child++)->getDoubleValue();
    Ey = (child++)->getDoubleValue();
    Ez = (child++)->getDoubleValue();
    donor_file = (child++)->getBooleanValue();
    electric_file = (child++)->getBooleanValue();
    U0 = (child++)->getDoubleValue();
    SurfacePassivation = getSurfacePassivationType((child++)->getStringValue());
    DanglingBondEnergyShift = (child++)->getDoubleValue();
    BondShift_s = (child++)->getDoubleValue();
    BondShift_p = (child++)->getDoubleValue();
    BondShift_d = (child++)->getDoubleValue();
    BondShift_sstar = (child++)->getDoubleValue();
    Disorder1 = (child++)->getDoubleValue();
    HbarOverTau = (child++)->getDoubleValue();

}

void Phys_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Phys_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            PotentialFile = (child++)->getStringValue();
            MagneticFieldOn = (child++)->getBooleanValue();
            Bx = (child++)->getDoubleValue();
            By = (child++)->getDoubleValue();
            Bz = (child++)->getDoubleValue();
            Bgauge = (child++)->getStringValue();
            ImpNumber = (child++)->getIntValue();
            ImpsXYZ = (child++)->getVectorDoubleValue();
            imp_model = (child++)->getIntValue();
            include_nuclear_term = (child++)->getBooleanValue();
            EfieldON = (child++)->getBooleanValue();
            Ex = (child++)->getDoubleValue();
            Ey = (child++)->getDoubleValue();
            Ez = (child++)->getDoubleValue();
            donor_file = (child++)->getBooleanValue();
            electric_file = (child++)->getBooleanValue();
            U0 = (child++)->getDoubleValue();
            SurfacePassivation = getSurfacePassivationType((child++)->getStringValue());
            DanglingBondEnergyShift = (child++)->getDoubleValue();
            BondShift_s = (child++)->getDoubleValue();
            BondShift_p = (child++)->getDoubleValue();
            BondShift_d = (child++)->getDoubleValue();
            BondShift_sstar = (child++)->getDoubleValue();
            Disorder1 = (child++)->getDoubleValue();
            HbarOverTau = (child++)->getDoubleValue();
            break;

        }
        index++;
    }
}

string Phys_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Phys_struct -----\n");
    output.append( string(indentSpacesMore) + string("PotentialFile: \"") + PotentialFile + string("\"\n"));
    sprintf(buffer, "%d", MagneticFieldOn);
    output.append( string(indentSpacesMore) + string("MagneticFieldOn: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Bx);
    output.append( string(indentSpacesMore) + string("Bx: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", By);
    output.append( string(indentSpacesMore) + string("By: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Bz);
    output.append( string(indentSpacesMore) + string("Bz: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("Bgauge: \"") + Bgauge + string("\"\n"));
    sprintf(buffer, "%d", ImpNumber);
    output.append( string(indentSpacesMore) + string("ImpNumber: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=ImpsXYZ.begin(); item != ImpsXYZ.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "ImpsXYZ[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    sprintf(buffer, "%d", imp_model);
    output.append( string(indentSpacesMore) + string("imp_model: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", include_nuclear_term);
    output.append( string(indentSpacesMore) + string("include_nuclear_term: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", EfieldON);
    output.append( string(indentSpacesMore) + string("EfieldON: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ex);
    output.append( string(indentSpacesMore) + string("Ex: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ey);
    output.append( string(indentSpacesMore) + string("Ey: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Ez);
    output.append( string(indentSpacesMore) + string("Ez: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", donor_file);
    output.append( string(indentSpacesMore) + string("donor_file: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", electric_file);
    output.append( string(indentSpacesMore) + string("electric_file: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", U0);
    output.append( string(indentSpacesMore) + string("U0: ") + string(buffer) + string("\n"));
    output.append( string(indentSpacesMore) + string("SurfacePassivation: enum ") + string(getEnumStringSurfacePassivationType(SurfacePassivation)) + string("\n") );
    sprintf(buffer, "%f", DanglingBondEnergyShift);
    output.append( string(indentSpacesMore) + string("DanglingBondEnergyShift: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", BondShift_s);
    output.append( string(indentSpacesMore) + string("BondShift_s: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", BondShift_p);
    output.append( string(indentSpacesMore) + string("BondShift_p: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", BondShift_d);
    output.append( string(indentSpacesMore) + string("BondShift_d: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", BondShift_sstar);
    output.append( string(indentSpacesMore) + string("BondShift_sstar: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", Disorder1);
    output.append( string(indentSpacesMore) + string("Disorder1: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", HbarOverTau);
    output.append( string(indentSpacesMore) + string("HbarOverTau: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Phys_struct -----\n");
    output.append("\n");
    return output;
}


