/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "RayleighRitz_struct.H"
#include "wiglafNode.H"

RayleighRitz_struct::RayleighRitz_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/Rayleigh-Ritz");
}

void RayleighRitz_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    MaxIter = (child++)->getIntValue();
    EigValGuess = (child++)->getVectorDoubleValue();
    ConvCrit = getConvCritType((child++)->getStringValue());
    StartFileRead = (child++)->getStringValue();
    verbose = (child++)->getIntValue();
    tol = (child++)->getDoubleValue();
    RunningIndex = (child++)->getIntValue();

}

void RayleighRitz_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "RayleighRitz_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            MaxIter = (child++)->getIntValue();
            EigValGuess = (child++)->getVectorDoubleValue();
            ConvCrit = getConvCritType((child++)->getStringValue());
            StartFileRead = (child++)->getStringValue();
            verbose = (child++)->getIntValue();
            tol = (child++)->getDoubleValue();
            RunningIndex = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string RayleighRitz_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin RayleighRitz_struct -----\n");
    sprintf(buffer, "%d", MaxIter);
    output.append( string(indentSpacesMore) + string("MaxIter: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<double>::iterator item=EigValGuess.begin(); item != EigValGuess.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "EigValGuess[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    output.append( string(indentSpacesMore) + string("ConvCrit: enum ") + string(getEnumStringConvCritType(ConvCrit)) + string("\n") );
    output.append( string(indentSpacesMore) + string("StartFileRead: \"") + StartFileRead + string("\"\n"));
    sprintf(buffer, "%d", verbose);
    output.append( string(indentSpacesMore) + string("verbose: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", tol);
    output.append( string(indentSpacesMore) + string("tol: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", RunningIndex);
    output.append( string(indentSpacesMore) + string("RunningIndex: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End RayleighRitz_struct -----\n");
    output.append("\n");
    return output;
}


