/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "ReadInEigen_struct.H"
#include "wiglafNode.H"

ReadInEigen_struct::ReadInEigen_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Electronic structure calculation/Algorithms/ReadInEigen");
}

void ReadInEigen_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    StateFileRead = (child++)->getStringValue();
    StateFileNumb = (child++)->getIntValue();

}

void ReadInEigen_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "ReadInEigen_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            StateFileRead = (child++)->getStringValue();
            StateFileNumb = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string ReadInEigen_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin ReadInEigen_struct -----\n");
    output.append( string(indentSpacesMore) + string("StateFileRead: \"") + StateFileRead + string("\"\n"));
    sprintf(buffer, "%d", StateFileNumb);
    output.append( string(indentSpacesMore) + string("StateFileNumb: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End ReadInEigen_struct -----\n");
    output.append("\n");
    return output;
}


