/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Shape_struct.H"
#include "wiglafNode.H"

Shape_struct::Shape_struct(const DOM_Node& dn) {
    set(dn,"/top/Geometric info/Shape List/Add a shape/ShapeName");
}

void Shape_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    Shape = getShapeType((child++)->getStringValue());
    has_cell_granularity = (child++)->getBooleanValue();
    use_for_strain_and_electronic = (child++)->getBooleanValue();
    xorigin = (child++)->getDoubleValue();
    yorigin = (child++)->getDoubleValue();
    zorigin = (child++)->getDoubleValue();
    x = (child++)->getDoubleValue();
    y = (child++)->getDoubleValue();
    z = (child++)->getDoubleValue();
    is_subdomain = (child++)->getBooleanValue();
    modify_species = (child++)->getBooleanValue();
    mat = (child++)->getVectorStringValue();
    mol = (child++)->getVectorDoubleValue();
    pol = (child++)->getVectorIntegerValue();
    AlloyTreatment = getAlloyTreatmentType((child++)->getStringValue());
    AlloyFixConcentration = (child++)->getBooleanValue();
    AlloyClusterRadius = (child++)->getIntValue();
    matid3d = (child++)->getIntValue();

}

void Shape_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Shape_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            Shape = getShapeType((child++)->getStringValue());
            has_cell_granularity = (child++)->getBooleanValue();
            use_for_strain_and_electronic = (child++)->getBooleanValue();
            xorigin = (child++)->getDoubleValue();
            yorigin = (child++)->getDoubleValue();
            zorigin = (child++)->getDoubleValue();
            x = (child++)->getDoubleValue();
            y = (child++)->getDoubleValue();
            z = (child++)->getDoubleValue();
            is_subdomain = (child++)->getBooleanValue();
            modify_species = (child++)->getBooleanValue();
            mat = (child++)->getVectorStringValue();
            mol = (child++)->getVectorDoubleValue();
            pol = (child++)->getVectorIntegerValue();
            AlloyTreatment = getAlloyTreatmentType((child++)->getStringValue());
            AlloyFixConcentration = (child++)->getBooleanValue();
            AlloyClusterRadius = (child++)->getIntValue();
            matid3d = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string Shape_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Shape_struct -----\n");
    output.append( string(indentSpacesMore) + string("Shape: enum ") + string(getEnumStringShapeType(Shape)) + string("\n") );
    sprintf(buffer, "%d", has_cell_granularity);
    output.append( string(indentSpacesMore) + string("has_cell_granularity: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", use_for_strain_and_electronic);
    output.append( string(indentSpacesMore) + string("use_for_strain_and_electronic: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", xorigin);
    output.append( string(indentSpacesMore) + string("xorigin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", yorigin);
    output.append( string(indentSpacesMore) + string("yorigin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", zorigin);
    output.append( string(indentSpacesMore) + string("zorigin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", x);
    output.append( string(indentSpacesMore) + string("x: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", y);
    output.append( string(indentSpacesMore) + string("y: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", z);
    output.append( string(indentSpacesMore) + string("z: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", is_subdomain);
    output.append( string(indentSpacesMore) + string("is_subdomain: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", modify_species);
    output.append( string(indentSpacesMore) + string("modify_species: ") + string(buffer) + string("\n"));
    i = 0;
    for (vector<string>::iterator item=mat.begin(); item != mat.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "mat[" + string(buffer) + "]: ");
        output.append(*item + "\n");
    }
    i = 0;
    for (vector<double>::iterator item=mol.begin(); item != mol.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "mol[" + string(buffer) + "]: ");
        sprintf(buffer, "%f", (double)*item);
        output.append( string(buffer) + "\n");
    }
    i = 0;
    for (vector<int>::iterator item=pol.begin(); item != pol.end(); item++) {
        sprintf(buffer, "%d", i++);
        output.append( string(indentSpacesMore) + "pol[" + string(buffer) + "]: ");
        sprintf(buffer, "%d", (int)*item);
        output.append( string(indentSpacesMore) + string(buffer) + "\n");
    }
    output.append( string(indentSpacesMore) + string("AlloyTreatment: enum ") + string(getEnumStringAlloyTreatmentType(AlloyTreatment)) + string("\n") );
    sprintf(buffer, "%d", AlloyFixConcentration);
    output.append( string(indentSpacesMore) + string("AlloyFixConcentration: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", AlloyClusterRadius);
    output.append( string(indentSpacesMore) + string("AlloyClusterRadius: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", matid3d);
    output.append( string(indentSpacesMore) + string("matid3d: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Shape_struct -----\n");
    output.append("\n");
    return output;
}


