/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "StrainOut_struct.H"
#include "wiglafNode.H"

StrainOut_struct::StrainOut_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Strain calculation/Output");
}

void StrainOut_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    EnergyFinal = (child++)->getBooleanValue();
    EnergyCGiter = (child++)->getBooleanValue();
    EnergyCGall = (child++)->getBooleanValue();
    Neighborhood = (child++)->getBooleanValue();
    Bondlength = (child++)->getBooleanValue();
    StrainElOnly = (child++)->getBooleanValue();
    TensionOutput = (child++)->getBooleanValue();
    DisplacementData = (child++)->getBooleanValue();
    DisplacementData3D = (child++)->getBooleanValue();
    LogLevel = (child++)->getIntValue();

}

void StrainOut_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "StrainOut_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            EnergyFinal = (child++)->getBooleanValue();
            EnergyCGiter = (child++)->getBooleanValue();
            EnergyCGall = (child++)->getBooleanValue();
            Neighborhood = (child++)->getBooleanValue();
            Bondlength = (child++)->getBooleanValue();
            StrainElOnly = (child++)->getBooleanValue();
            TensionOutput = (child++)->getBooleanValue();
            DisplacementData = (child++)->getBooleanValue();
            DisplacementData3D = (child++)->getBooleanValue();
            LogLevel = (child++)->getIntValue();
            break;

        }
        index++;
    }
}

string StrainOut_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin StrainOut_struct -----\n");
    sprintf(buffer, "%d", EnergyFinal);
    output.append( string(indentSpacesMore) + string("EnergyFinal: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", EnergyCGiter);
    output.append( string(indentSpacesMore) + string("EnergyCGiter: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", EnergyCGall);
    output.append( string(indentSpacesMore) + string("EnergyCGall: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Neighborhood);
    output.append( string(indentSpacesMore) + string("Neighborhood: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", Bondlength);
    output.append( string(indentSpacesMore) + string("Bondlength: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", StrainElOnly);
    output.append( string(indentSpacesMore) + string("StrainElOnly: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", TensionOutput);
    output.append( string(indentSpacesMore) + string("TensionOutput: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", DisplacementData);
    output.append( string(indentSpacesMore) + string("DisplacementData: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", DisplacementData3D);
    output.append( string(indentSpacesMore) + string("DisplacementData3D: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%d", LogLevel);
    output.append( string(indentSpacesMore) + string("LogLevel: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End StrainOut_struct -----\n");
    output.append("\n");
    return output;
}


