/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Strain_struct.H"
#include "wiglafNode.H"

Strain_struct::Strain_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Strain calculation");
}

void Strain_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    StrainModel = getStrainModelType((child++)->getStringValue());

    Keating.set(dn,"/top/Execution parameters/Strain calculation/Keating");
    StrainOut.set(dn,"/top/Execution parameters/Strain calculation/Output");
}

void Strain_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Strain_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            StrainModel = getStrainModelType((child++)->getStringValue());
            break;

        }
        index++;
    }
}

string Strain_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Strain_struct -----\n");
    output.append( string(indentSpacesMore) + string("StrainModel: enum ") + string(getEnumStringStrainModelType(StrainModel)) + string("\n") );

    output.append( Keating.toString(indentLength) );
    output.append( StrainOut.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End Strain_struct -----\n");
    output.append("\n");
    return output;
}


