/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "Subdomain_struct.H"
#include "wiglafNode.H"

Subdomain_struct::Subdomain_struct(const DOM_Node& dn) {
    set(dn,"/top/Execution parameters/Subdomain");
}

void Subdomain_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    xMin = (child++)->getDoubleValue();
    yMin = (child++)->getDoubleValue();
    zMin = (child++)->getDoubleValue();
    xMax = (child++)->getDoubleValue();
    yMax = (child++)->getDoubleValue();
    zMax = (child++)->getDoubleValue();

}

void Subdomain_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "Subdomain_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            xMin = (child++)->getDoubleValue();
            yMin = (child++)->getDoubleValue();
            zMin = (child++)->getDoubleValue();
            xMax = (child++)->getDoubleValue();
            yMax = (child++)->getDoubleValue();
            zMax = (child++)->getDoubleValue();
            break;

        }
        index++;
    }
}

string Subdomain_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin Subdomain_struct -----\n");
    sprintf(buffer, "%f", xMin);
    output.append( string(indentSpacesMore) + string("xMin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", yMin);
    output.append( string(indentSpacesMore) + string("yMin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", zMin);
    output.append( string(indentSpacesMore) + string("zMin: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", xMax);
    output.append( string(indentSpacesMore) + string("xMax: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", yMax);
    output.append( string(indentSpacesMore) + string("yMax: ") + string(buffer) + string("\n"));
    sprintf(buffer, "%f", zMax);
    output.append( string(indentSpacesMore) + string("zMax: ") + string(buffer) + string("\n"));

    output.append( string(indentSpaces) + "---- End Subdomain_struct -----\n");
    output.append("\n");
    return output;
}


