/* This file is automatically generated.  DO NOT EDIT! */

#include "domStuff.H"
#include "top_struct.H"
#include "wiglafNode.H"

top_struct::top_struct(const DOM_Node& dn) {
    set(dn,"/top");
}

void top_struct::set(const DOM_Node& dn, string s) {
    wiglafNode w(dn,s);
    vector<wiglafNode> g = w.getChildren(isParamButNotDeleteBranch);
    vector<wiglafNode>::iterator child=g.begin();

    Version = (child++)->getStringValue();
    pythonFuncsFile = (child++)->getStringValue();

    Dev.set(dn,"/top/Geometric info");
    vector<wiglafNode> allGroupsInTypeStruct = w.getChildren(isGroup);
    Material_struct item;
    for (vector<wiglafNode>::iterator groupInTypeStruct = allGroupsInTypeStruct.begin(); groupInTypeStruct != allGroupsInTypeStruct.end(); groupInTypeStruct++ ) {
        if ( groupInTypeStruct->getAttribute("type").equals("array") ) {
            int offset = 0;
            vector<wiglafNode> allGroupsInTypeArray = groupInTypeStruct->getChildren(isGroup);
            for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
                if ( groupInTypeArray->getAttribute("type").equals("obj") ) {
                    item.setFromArrayElement(dn,groupInTypeStruct->getPathToRoot(),offset++);
                    material_list.push_back(item);
                }
            }
        }
    }
    ExecParam.set(dn,"/top/Execution parameters");
}

void top_struct::setFromArrayElement(const DOM_Node& dn,  string pathToArray, int offset) {
    wiglafNode w(dn,pathToArray);

    if (!( w.getElementName().equals("group") || w.getAttribute("type").equals("array") )) {
        cerr << "top_struct::setFromArrayElement(): wiglafNode is not <group type=array> !\n";
        return;
    }

    int index = 0;
    vector<wiglafNode> allGroupsInTypeArray = w.getChildren(isGroup);
    for (vector<wiglafNode>::iterator groupInTypeArray = allGroupsInTypeArray.begin(); groupInTypeArray != allGroupsInTypeArray.end(); groupInTypeArray++ ) {
        if ( groupInTypeArray->getAttribute("type").equals("obj") && (index == offset) ) {

            vector<wiglafNode> g = groupInTypeArray->getChildren(isParamButNotDeleteBranch);
            vector<wiglafNode>::iterator child=g.begin();
            Version = (child++)->getStringValue();
            pythonFuncsFile = (child++)->getStringValue();
            break;

        }
        index++;
    }
}

string top_struct::toString(int indentLength) {
    int i;
    char buffer[20];
    const string Indent("    ");

    string indentSpaces;
    for (i=0; i<indentLength; i++) {;
        indentSpaces.append(Indent);
    }
    string indentSpacesMore = string(indentSpaces+Indent);
    indentLength++;

    string output( string(indentSpaces) + "---- Begin top_struct -----\n");
    output.append( string(indentSpacesMore) + string("Version: \"") + Version + string("\"\n"));
    output.append( string(indentSpacesMore) + string("pythonFuncsFile: \"") + pythonFuncsFile + string("\"\n"));

    output.append( Dev.toString(indentLength) );
    for (vector<Material_struct>::iterator item = material_list.begin(); item != material_list.end(); item++ ) {
        output.append( item->toString(indentLength) );
    }
    output.append( ExecParam.toString(indentLength) );
    output.append( string(indentSpaces) + "---- End top_struct -----\n");
    output.append("\n");
    return output;
}


