var annotated_dup =
[
    [ "AngularMomentum", "class_angular_momentum.html", null ],
    [ "argv_array_t", "structargv__array__t.html", null ],
    [ "argv_t", "structargv__t.html", null ],
    [ "argv_type_t", "structargv__type__t.html", null ],
    [ "Cell", "class_cell.html", "class_cell" ],
    [ "CMD_OPTIONS", "struct_c_m_d___o_p_t_i_o_n_s.html", null ],
    [ "Coulomb", "class_coulomb.html", null ],
    [ "Decoherence", "class_decoherence.html", null ],
    [ "Dipole", "class_dipole.html", null ],
    [ "geo_struct", "classgeo__struct.html", "classgeo__struct" ],
    [ "GEOPOINT", "struct_g_e_o_p_o_i_n_t.html", null ],
    [ "HamStore", "class_ham_store.html", null ],
    [ "HamZincBlende", "class_ham_zinc_blende.html", null ],
    [ "HamZincBlendeComplex", "class_ham_zinc_blende_complex.html", null ],
    [ "MaterialHandle", "class_material_handle.html", null ],
    [ "MatSite_Init_struct", "struct_mat_site___init__struct.html", null ],
    [ "mpiCommClass", "classmpi_comm_class.html", null ],
    [ "ostream_N3D", "classostream___n3_d.html", null ],
    [ "phon_struct", "classphon__struct.html", "classphon__struct" ],
    [ "POLYSHAPESTRUCT", "struct_p_o_l_y_s_h_a_p_e_s_t_r_u_c_t.html", null ],
    [ "Projection", "class_projection.html", null ],
    [ "QD_struct", "class_q_d__struct.html", "class_q_d__struct" ],
    [ "RandRandom", "class_rand_random.html", null ],
    [ "StrainComm", "class_strain_comm.html", null ],
    [ "StrainParam", "class_strain_param.html", "class_strain_param" ],
    [ "streambuf_N3D", "classstreambuf___n3_d.html", null ],
    [ "TimeReversal", "class_time_reversal.html", null ],
    [ "waveFunction", "classwave_function.html", null ]
];