/*****************************************************************************
The Jet Propulsion Laboratory (JPL) XML-to-C++ package.
Copyright (C) 2002 California Institute of Technology (Caltech)

This library is free software, which you can redistribute and/or modify
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; see the file COPYING. If not, write to the
Free Software Foundation, Inc.,
59 Temple Place, Suite 330,
Boston, MA  02111-1307  USA

For additional information, please contact
  Fabiano Oyafuso (fabiano@jpl.nasa.gov)

Written by:  Fabiano Oyafuso
             Hook Hua
             Ed Vinyard

This product includes software developed by the Apache Software Foundation
(http://www.apache.org/).
*****************************************************************************/

#ifndef _DOMSTUFF_H
#define _DOMSTUFF_H

#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/util/XMLString.hpp>
#include <xercesc/util/XMLUniDefs.hpp>
#include <xercesc/util/TranscodingException.hpp>
#include <xercesc/framework/XMLFormatter.hpp>
#include <xercesc/dom/deprecated/DOM_DOMException.hpp>
#include <xercesc/dom/deprecated/DOMParser.hpp>
#include <xercesc/dom/deprecated/DOM.hpp>
#include "DOMTreeErrorReporter.H"

#endif /* _DOMSTUFF_H */

