function [dat] = getVar(type, run, indx)

%  getVar: [real(m,n) dat] <-- (string type, string run, OPT int indx)
%
%==============================================================================
%
%  DESCRIPTION:
%
%    This wrapper around readData returns a matrix generated from
%    NEMO-3D input data (see help on readData)
%    
%  INPUT:
%
%    string type:   describes the physical nature of the data to be read in.
%                   Possible values include:
%
%                       'wf'   (probability density)
%                       'wv'   (eigenvector)
%                       'Req'  (equilibrium atom position)
%                       'R'    (strained atomic positions)
%                       'Rwf'  (strained atomic positions + prob. density)
%                       'disp' (displacment information)
%                       'type' (atomic type information)
%
%    string run:    name (prefix) of the run.  For example if the data
%                   file was generated by 'test.in', then 'test' would
%                   be the prefix.
%
%    OPTIONAL int indx:  for probability density and eigenvector types,
%                        this string is required and equals the
%                        eigenvalue index determined by NEMO-3D.
%
%  OUTPUT:
%
%    real(m,n) dat:  return data in the form of an mxn matrix
%
%  DEPENDENCIES: readData
%
%==============================================================================

srchDir = getenv('MATLAB_DATAPATH');
if (size(srchDir,1)==0);  srchDir = ['./'];  end

if     (strcmp(type,'wf'))
  dat = readData([srchDir run '.nd_wf_' num2str(indx)]);
elseif (strcmp(type,'Rwf'))
  dat = [ readData([srchDir run '.nd_rAtom']) ...
          readData([srchDir run '.nd_wf_' num2str(indx)]) ];
elseif (strcmp(type,'wv'))
  dat = readData([srchDir run '.nd_evec_' num2str(indx)]);
elseif (strcmp(type,'Req'))
  dat = readData([srchDir run '.nd_rAtomEquil']);
elseif (strcmp(type,'R'))
  dat = readData([srchDir run '.nd_rAtom']);
elseif (strcmp(type,'disp'))
  dat = readData([srchDir run '.nd_disp']);
elseif (strcmp(type,'type'))
  dat = readData([srchDir run '.nd_aType']);
else
  disp('undefined type');
  dat = [];
end
