function [ptr_fig] = plLanczProg(fil)

% plLanczProg:  [ptr_fig] <-- (fil)
%
%==============================================================================
%
%  DESCRIPTION:
%
%    Plots trace of eigenvalues generated by Lanczos algorithm
%
%  INPUT:
%
%    string fil:  Ascii input file; '.nd_eval_trace' may be omitted
%
%  OUTPUT:
%
%    pointer to plot
%
%  DEPENDENCIES: none
%
%==============================================================================

fp = fopen(fil,'r');
if (fp == -1)
   fil = [fil '.nd_eval_trace'];
   fp = fopen(fil,'r');
end
if (fp == -1)
   disp(['Unable to open file:  ' file]); ptr_fig=[]; return;
end

dum=load(fil);

ptr_fig=plot(dum(:,1),dum(:,2),'.');
xlabel('lanczos iterations');
ylabel('energy');

