function [H, Mv] = plPsi2_scat(run, ev_indx, ampl, usr) 

%  plPsi2_scat:  [H, Mv] <-- (run, ev_indx, ampl, usr)
%
%==============================================================================
%
%  DESCRIPTION:
%
%    Generates an array of plot handles to scatter plots generated
%    by restricting the values of col 4 of g.  Optionally generate a movie,
%    that steps through the wavefunction amplitude.
%
%  INPUT:
%
%    string run:    name (prefix) of the run.  For example if the data
%                   file was generated by 'test.in', then 'test' would
%                   be the prefix.
%
%    int indx:      for probability density and eigenvector types,
%                   this string is required and equals the
%                   eigenvalue index determined by NEMO-3D.
%
%    real(n) ampl:  represents a sequence of contiguous disjoint intervals
%                   to which psi2(x,y,z) is restricted.  For example,
%                    
%                           ampl = [1 .5 .3];
%
%                   will plot all R such that 0.3 < psi2(R) < 0.5 and also
%                   all R such that 0.5 < psi2(R) < 1.0.  These two plots
%                   are colored differently.
%    
%    string usr:    this string is evaluated within matlab and is used
%                   to set the following optional variables:
%
%                   nrm:  if not defined, psi2 is not normalized
%                         if equal to 2, psi2 is normalized by the 2-norm
%                         if equal to inf, psi2 is normalized by max(psi2)
%                    
%                   mov:  if defined, a new plot is created, making a movie.
%                         if not, the plots are superimposed.  
%
%                   big:  if defined, the plotting domain is enlarged to
%                         accommodate rotations
%
%                   fil:  print to file, if string not specified,
%                         print to [run '-' ev_indx '_scat.eps']
%
%  OUTPUT:
%
%    plot(m) H:     array of handles to plots
%
%    movie  Mv:     if a movie is generated, this is non-null.
%
%
%  EXAMPLES:
%
%    Typical simple plot:  H = plPsi2_scat('run', 1, [1 .6 .5 .4])
%
%    Typical plot using normalized psi: 
%
%                          H=plPsi2_scat('run',1,[1 .02 .005],'nrm=2;')
%
%    Typical movie:  [H, Mv] = plPsi2_scat('run', 1, [1:-.01:.1],'mov=1;')
%                    movie(Mv);
%
%  COMMON ERRORS:  
%  
%    an error frequently made is that none of the amplitude ranges contains
%    any points in wavefunction.  Also, note that for historical reasons,
%    ampl is a monotonically DECREASING sequence of reals.
%
%  DEPENDENCIES:  plScat  prettyPlot
%
%==============================================================================

psi2 = getVar('Rwf', run, ev_indx);

if ( exist('usr') )
   [H Mv] = plScat(psi2, ampl, usr);
else
   [H Mv] = plScat(psi2, ampl);
end

if ( exist('usr') );  eval(usr); end

if ( exist('fil') )
   if (isempty(fil));  fil=[run '-' num2str(ev_indx) '_scat']
end
   dum = ['bx=1; gr=1; sh=''square''; ps=''' fil ''';'];
   prettyPlot(dum);
   disp(['wrote to file: ''' fil '''']);
end
