function [A] = readData(filename, usr)

%  readData:  [real(m,n) A] <-- (string filename, string usr)
%
%==============================================================================
%
%  DESCRIPTION:
%
%    Read in data of the form generated by NEMO-3D and return in the
%    form of a matrix.  A NEMO-3D data file of the type used as input
%    consists of two parts:  an ascii header followed by binary data.
%    An example of a header is shown below:
%
%         <HDR>
%           record format        = {real x, real y}
%           record dimension 1   = 10000             # number of atoms
%           user data 1          = Bands_20_s        # band_model
%           user data 2          = 2                 # crystal structure
%         <\HDR>
%
%    In this example, the binary data that follow will be returned
%    in matrix of size 10000x2.  At the moment, this function has the
%    following two limitations:
%        (1) the binary data following the header can be of only one type
%        (2) there must be a 'user data' key or at least a '=' following 
%            the row dimension info.                         
%
%  INPUT:
%    
%    string filename :  name of the file to be opened
%
%    string usr:        a string to be evaluated within matlab
%
%  OUTPUT:
%
%    real(m,n) A:       return data in the form of an mxn matrix
%
%  DEPENDENCIES: none
%                                                          
%==============================================================================

if ( exist('usr') );  eval(usr);  end

srchDir = getenv('MATLAB_DATAPATH');
if (size(srchDir,1)==0);  srchDir = ['.'];  end

fp = fopen([srchDir '/' filename],'r');
if (fp == -1)
   disp(['Could not find file ' filename]);  return
end

% first entry must be the record format
fscanf(fp,'%[^=]s',1); fscanf(fp,'%c',1);
fmt_str=fscanf(fp,'%[^\n]s',1);

indxInt = findstr(fmt_str,'int');
indxReal = findstr(fmt_str,'real');

% ASSUME there is user data after dimension info!
dim=[];
dim_prod = 1;
while (fp ~= 0)
   key=fscanf(fp,'%[^=]s',1); fscanf(fp,'%c',1);
   if ( isempty(findstr(key,'dimension')) )
      break;
   end
   this_dim = fscanf(fp,'%d',1);
   dim=[dim this_dim];
   dim_prod = dim_prod * this_dim;
   fscanf(fp,'%[^\n]',1);
end

while (fp ~= 0)
   junk=fscanf(fp,'%[^>]',1);
   if ( isempty(findstr(key,'<\HDR')) )
      fscanf(fp,'%c',1);
      break;
   end  
end

% read in file
if     ( isempty(indxInt) )
   A = fread(fp, [size(indxReal,2) dim_prod], 'double');
elseif ( isempty(indxReal) )
   A = fread(fp, [size(indxInt,2) dim_prod], 'int');
else
   disp('Data can only be of one type -- either all double or all int');
   A = [];
end

A = A';
fclose(fp);
