function [R_line, ep_line, a_line] = strain_tensor(fil, atomType, drct, bx)

%  strain_tensor:  [R_line, ep_line, a_line] <-- (fil, atomType, drct, bx)
%
%==============================================================================
%
%  DESCRIPTION:
%
%    Computes the strain tensor along a thin tube.
%    Caveat:  This function has not been well-tested.  Also, the interface
%             to this function is likely to change in the future.
%             Use at your own risk!!!
%
%  INPUT:
%
%    string fil:  Ascii input file of the following format:
%
%                     col  1    = atomType
%                     col  2-4  = position (R) 
%                     col  5-7  = displacement of neighbor 1
%                     col  8-10 = displacement of neighbor 2
%                     col 11-13 = displacement of neighbor 3
%                     col 14-16 = displacement of neighbor 4
%                     col 17-19 = unstrained displacement of neighbor 1
%                     col 20-22 = unstrained displacement of neighbor 2
%                     col 23-25 = unstrained displacement of neighbor 3
%                     col 26-28 = unstrained displacement of neighbor 4
%
%                 Such a file is generated by concatenating the outputs
%                 of <run>.nd_bondLen_* generated by run3d.
%
%    string atomType:  atom species to plot; can be 'Ga', 'In', 'As', 
%                      or 'all' (default)
%
%    int drct: Axis of tube.  Possible values include {1 (x), 2 (y), 3 (z)}
%
%    real[6] bx:  bounding box used to further constrain the data.
%
%  OUTPUT:
%
%    real(n) R_line:     positions of points in fil subject to the constraint
%                        specified by bx and projected along the axis specified
%                        by drct.
%
%    real(3,n) ep_line:  diagonal components of strain tensor as a function
%                        of position determined by R_line.  For example,
%                        ep_line(:,n) is the diagonal part of the strain 
%                        tensor at R_line(n).
%
%    real(3,n) a_line:   The nth column of a_line are the lattice constants
%                        in the x, y, and z directions at position R_line(n)
%
%  EXAMPLES:  here is a basic use of this function --
%
%    [r,ep,a]=strain_tensor('test.nd_bondLen','Ga',1);
%
%  DEPENDENCIES: none
%
%==============================================================================

if (~exist('fil')); disp('Must specify a file'); return; end;
if (~exist('atomType')); atomType='all'; end;
if (~exist('drct')); drct=1; end;
if (~exist('bx')); bx=[0 99 0 99 0 99]; end;

eye3 = eye(3);

b=load(fil);
Natom = size(b,1);
pos = b(:,[2:4]);

indx=find(pos(:,1) > bx(1) & pos(:,1) < bx(2) & ...
          pos(:,2) > bx(3) & pos(:,2) < bx(4) & ...
          pos(:,3) > bx(5) & pos(:,3) < bx(6));

posr = pos(indx,:);
br = b(indx,:);

ep=ones(3,size(br,1));
a=ones(3,size(br,1));

for j = 1:size(br,1);

   r1 = br(j,5:7);
   r2 = br(j,8:10);
   r3 = br(j,11:13);
   r4 = br(j,14:16);
   r01 = br(j,17:19);
   r02 = br(j,20:22);
   r03 = br(j,23:25);
   r04 = br(j,26:28);

   ax = r2 + r3 - r4 - r1;
   ay = r3 + r4 - r2 - r1;
   az = r2 + r4 - r3 - r1;
   ax0 = r02 + r03 - r04 - r01;
   ay0 = r03 + r04 - r02 - r01;
   az0 = r02 + r04 - r03 - r01;

   if (br(j,1)==12)
      az = -az;
      az0 = -az0;
   end
   R = [ax' ay' az'];
   R0 = [ax0' ay0' az0'];

   e=R*inv(R0) - eye3;

   ep(:,j)= diag(e);
   a(:,j) = [ax(1); ay(2); az(3)];

   if (mod(j,1000)==0);  disp(num2str(j/1000));  end
end


if (strcmp(atomType,'all'))
   R_line = posr(:,drct);
   ep_line = ep;
   a_line = a;
else
   if (strcmp(atomType,'Ga'))
      indx=find(br(:,1)==10);
   elseif (strcmp(atomType,'In'))
      indx=find(br(:,1)==14);
   elseif (strcmp(atomType,'As'))
      indx=find(br(:,1)==12);
   end

   R_line = posr(indx,drct);
   ep_line = ep(:,indx);
   a_line = a(:,indx);
end
