#!/bin/tcsh
#PBS -me -l nodes=1:ppn=1,walltime=10:00:00
#PBS -q ncn
#PBS -o poisson3d.out
#PBS -e poisson3d.err

# name of the poisson3d executable 
set executable="/autohome/u106/ssahmed/DEVELOP/NEMO_3D_0619/NEMO_3D/piezoelectricityNEMO3D/poissonNEMO3D/bin/poisson3d.ex"
echo $executable

cd $PBS_O_WORKDIR

set machinefile=`basename $PBS_NODEFILE`
cp $PBS_NODEFILE machinefile.txt

set cmd="$executable MY_INPUT_FILE_1 MY_INPUT_FILE_2 MY_INPUT_FILE_3"
echo $cmd
$cmd
