      COMMON/fund const/q,debye,Vt,Rni
      COMMON/semicond/eps_si,eps_ox,eps_p,eps_gaas,eps_inas,eps_ingaas
      COMMON/iteration/delta_max,k_iter,i_err,j_err,k_err
      common/ngrid/nx,ny,nz,k_ox
      common/atom/dx1,dy1,dz1
      common/domain/xmax,xmin,ymax,ymin,zmax,zmin
      common/nnc/nn
      common/nnc1/strain_file
      common/nnc2/z_contour

      character*80 strain_file
      real*8 T,pi,k_b,h,hb,Vt
